### ISSUE TITLE
"course-sdk test" fails on Windows because tmp.file() doesn't work in Bun

### ISSUE THREAD

**Issue by DanTup** [codecrafters-io/course-sdk#19]
This is what I get when trying to use `course-sdk test` on Windows:

```
PS C:\Dev\CodeCrafters\build-your-own-http-server> course-sdk test dart
Compiling... (use --no-compile to skip)
Building js-tools Docker image...

Calling fs.openSync("C:\Users\danny\AppData\Local\Temp\tmp-12592-GuAvLXQQtHRx", 1282, 384)
167 |     opts = args[0];
168 |
169 |   const discardOrDetachDescriptor = opts.discardDescriptor || opts.detachDescriptor;
170 |   const name = tmpNameSync(opts);
171 |   console.log(`Calling fs.openSync("${name}", ${CREATE_FLAGS}, ${opts.mode || FILE_MODE})`);
172 |   var fd = fs.openSync(name, CREATE_FLAGS, opts.mode || FILE_MODE);
                    ^
ENOENT: No such file or directory
   errno: -2
 syscall: "open"
   path: "C:\Users\danny\AppData\Local\Temp\tmp-12592-GuAvLXQQtHRx"

      at fileSync (C:\Dev\CodeCrafters\course-sdk\node_modules\tmp\lib\tmp.js:172:15)
      at C:\Dev\CodeCrafters\course-sdk\lib\docker-shell-command-executor.ts:26:32
      at buildImage (C:\Dev\CodeCrafters\course-sdk\lib\docker-shell-command-executor.ts:25:27)
      at C:\Dev\CodeCrafters\course-sdk\commands\compile.ts:23:38
      at doRun (C:\Dev\CodeCrafters\course-sdk\commands\compile.ts:18:17)
      at C:\Dev\CodeCrafters\course-sdk\commands\base.ts:6:16
      at run (C:\Dev\CodeCrafters\course-sdk\commands\base.ts:5:15)
      at C:\Dev\CodeCrafters\course-sdk\cli.ts:38:48
      at C:\Dev\CodeCrafters\course-sdk\cli.ts:31:18

Bun v1.1.13 (Windows x64)
```

The line of code failing is this:

https://github.com/codecrafters-io/course-sdk/blob/475d01491d5304a81fb48f9ea9cdbd9b2b264fc8/lib/docker-shell-command-executor.ts#L26

It's using the `tmp` package from `npm` to create a temp file, which internally calls:

```js
var fd = fs.openSync(name, CREATE_FLAGS, opts.mode || FILE_MODE);
```

The definition of `CREATE_FLAGS` is:

```
CREATE_FLAGS = (_c.O_CREAT || _c.fs.O_CREAT) | (_c.O_EXCL || _c.fs.O_EXCL) | (_c.O_RDWR || _c.fs.O_RDWR),
```

This appears to not work for me on Windows with Bun. If I create a `.js` file like:

```js
import tmp from "tmp";

console.log(tmp.fileSync().name);
```

It works fine on node, but fails with bun:

```
PS C:\Dev\CodeCrafters\course-sdk> node .\danny.js
Calling fs.openSync("C:\Users\danny\AppData\Local\Temp\tmp-10900-Rw7jt3j7ND5y", 1282, 384)
C:\Users\danny\AppData\Local\Temp\tmp-10900-Rw7jt3j7ND5y
PS C:\Dev\CodeCrafters\course-sdk> bun .\danny.js
Calling fs.openSync("C:\Users\danny\AppData\Local\Temp\tmp-16428-duMHLM847XLq", 1282, 384)
167 |     opts = args[0];
168 |
169 |   const discardOrDetachDescriptor = opts.discardDescriptor || opts.detachDescriptor;
170 |   const name = tmpNameSync(opts);
171 |   console.log(`Calling fs.openSync("${name}", ${CREATE_FLAGS}, ${opts.mode || FILE_MODE})`);
172 |   var fd = fs.openSync(name, CREATE_FLAGS, opts.mode || FILE_MODE);
                    ^
ENOENT: No such file or directory
   errno: -2
 syscall: "open"
   path: "C:\Users\danny\AppData\Local\Temp\tmp-16428-duMHLM847XLq"

      at fileSync (C:\Dev\CodeCrafters\course-sdk\node_modules\tmp\lib\tmp.js:172:15)
      at C:\Dev\CodeCrafters\course-sdk\danny.js:3:17

Bun v1.1.13 (Windows x64)
```

I don't know if this is a bug in `tmp` or in `bun` but I thought it was worth having an issue for here (assuming Windows support for course-sdk is a reasonable goal). It might be easier to change course-sdk than wait for an upstream fix.

Edit: I've opened https://github.com/oven-sh/bun/issues/11873 (assuming the underlying issue is bun).

**Comment by DanTup** [comment]
While working more on getting Dart working, I realised there are other things here that aren't Windows-friendly (like having `./your_server.sh` to start the server). Maybe supporting Windows is more involved than I realised and is not a goal (it's a shame though, given how many of the languages are cross-platform 🙂)

**Comment by rohitpaulk** [comment]
@DanTup yep, there's likely a bunch of other work to make this Windows-friendly 🙂 Our current recommendation in our installation docs is for folks to use WSL if possible. We do want to support Windows natively someday, just don't have the bandwidth at the moment.
